# 錯誤處理

```csharp
async Task Main()
{
    CancellationTokenSource cts = new CancellationTokenSource(100);

    var tasks = new[]{
        PrintAsync(cts.Token),
        PrintAsync(cts.Token, true),
        PrintAsync(cts.Token),
    };

    try
    {
        await Task.WhenAll(tasks);
    }
    catch (OperationCanceledException)
    {
        foreach (var t in tasks.Where(t => t.IsCanceled))
        {
            Console.WriteLine($"Task Id:{t.Id} Canceled !!");
        }

        foreach (var t in tasks.Where(t => t.IsFaulted))
        {
            Console.WriteLine($"Task Id:{t.Id} Faulted !! {t.Exception.Message}");
        }
    }
    catch(Exception)
    {
        foreach (var t in tasks.Where(t => t.IsFaulted))
        {
            Console.WriteLine($"Task Id:{t.Id} Faulted !! Exception Message:{t.Exception.Message} Inner Exception Message:{t.Exception.InnerException.Message} ");
        }
    }

    foreach (var t in tasks.Where(t => t.Status == TaskStatus.RanToCompletion))
    {
        Console.WriteLine($"Task Id:{t.Id} Completed !!");
    }
}

private async Task PrintAsync(CancellationToken token, bool hasError = false)
{
    await Task.Delay(10);

    if (token.IsCancellationRequested)
    {
        // "Cancelled".Dump();
        token.ThrowIfCancellationRequested();
        return;
    }

    if (hasError)
    {
        throw new Exception("Test Error");
    }

    Console.WriteLine($"Thread Id:{Thread.CurrentThread.ManagedThreadId}");
}
```
